#!/usr/bin/env python3
"""Build deterministic projections from canonical Markdown decision records."""
from __future__ import annotations
import argparse, hashlib, json, re
from pathlib import Path
from typing import Any

START = "<!-- DECISION-EVIDENCE-JSON"
END = "END-DECISION-EVIDENCE-JSON -->"
GENERATED = (
    "decision-evidence-index.yaml",
    "DECISION-EVIDENCE-INDEX.md",
    "CONSTRAINTS-PILOT-PROJECTION.md",
    "equivalence-report.md",
)

def extract_record(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise ValueError(f"{path}: missing canonical machine block")
    payload = text.split(START, 1)[1].split(END, 1)[0].strip()
    return json.loads(payload)

def load_records(repo_root: Path) -> list[dict[str, Any]]:
    paths = sorted((repo_root / "docs/evidence/records").glob("*.md"))
    records = [extract_record(p) for p in paths]
    return sorted(records, key=lambda r: r["id"])

def compact_source(source: dict[str, Any]) -> str:
    locator = source.get("locator") or source.get("json_pointer")
    return f"{source['path']}#{locator}"

def compact_record(record: dict[str, Any]) -> dict[str, Any]:
    projected = {
        "canonical_record": f"docs/evidence/records/{record['id']}.md",
        "claims": [
            {
                "display": claim["display"],
                "name": claim["name"],
                "population": claim["population"],
                "source": compact_source(claim["source"]),
                "strength": claim["evidence_strength"],
            }
            for claim in record["decisive_claims"]
        ],
        "conclusion": record["conclusion"],
        "cost_class": record["cost"]["class"],
        "discussions": record.get("discussions", []),
        "evidence_strength": record["primary_evidence_strength"],
        "id": record["id"],
        "kind": record["kind"],
        "relations": [
            f"{relation['type']}:{relation['target']}"
            for relation in record.get("relations", [])
        ],
        "scope": record["scope"],
        "status": record["status"],
    }
    if record.get("outcomes"):
        projected["outcomes"] = record["outcomes"]
    if record.get("premise_failure"):
        projected["premise_failure"] = record["premise_failure"]
    return projected

def render_yaml(records: list[dict[str, Any]]) -> str:
    # Compact JSON is valid YAML 1.2. Canonical records remain the authority; this is navigation.
    projection = {
        "canonical_format": "docs/evidence/records/*.md#DECISION-EVIDENCE-JSON",
        "records": [compact_record(record) for record in records],
        "schema": "decision-evidence-index-v1",
    }
    return json.dumps(
        projection,
        sort_keys=True,
        ensure_ascii=False,
        separators=(",", ":"),
    ) + "\n"

def render_index(records: list[dict[str, Any]]) -> str:
    closed = sum(r["status"] in {"closed", "invalidated"} for r in records)
    void = sum(r["status"] == "void-premise" for r in records)
    lines = [
        "# Decision and Evidence Index — pilot",
        "",
        "Generated from canonical Markdown records. Do not edit this file by hand.",
        "",
        f"- Records: **{len(records)}**",
        f"- Scientific closures/invalidations: **{closed}**",
        f"- Void-premise records (excluded from closure count): **{void}**",
        "",
        "| ID | Status | Kind | Decision | Primary evidence | Cost |",
        "|---|---|---|---|---|---|",
    ]
    for r in records:
        conclusion = r["conclusion"].replace("|", "\\|")
        lines.append(
            f"| [{r['id']}](../records/{r['id']}.md) | `{r['status']}` | "
            f"`{r['kind']}` | {conclusion} | `{r['primary_evidence_strength']}` | "
            f"{r['cost']['class']} |"
        )
    lines += ["", "## Open discussions", ""]
    discussions = [(r["id"], d) for r in records for d in r.get("discussions", [])]
    if discussions:
        for rid, did in discussions:
            lines.append(f"- [{did}](../discussions/{did}.md) — affects `{rid}`")
    else:
        lines.append("- None.")
    return "\n".join(lines) + "\n"

def render_constraints(records: list[dict[str, Any]]) -> str:
    groups: dict[str, list[dict[str, Any]]] = {}
    for r in records:
        groups.setdefault(r["constraint_projection"]["section"], []).append(r)
    lines = [
        "# CONSTRAINTS pilot projection",
        "",
        "Generated review artifact. This does **not** replace or modify `docs/CONSTRAINTS.md`.",
        "",
    ]
    for section in sorted(groups):
        lines += [f"## {section}", ""]
        for r in sorted(groups[section], key=lambda x: x["id"]):
            lines.append(f"- {r['constraint_projection']['bullet']}")
        lines.append("")
    return "\n".join(lines)

def numeric_tokens(text: str) -> list[str]:
    return re.findall(r"(?<![A-Za-z])[-+−±]?\d+(?:\.\d+)?(?:/\d+)?%?", text)

def render_equivalence(records: list[dict[str, Any]]) -> str:
    lines = [
        "# Pilot CONSTRAINTS equivalence report",
        "",
        "Every row maps a canonical record to the existing binding source and the generated",
        "projection. Numeric-token coverage is checked mechanically by the validator.",
        "",
        "| Record | Binding source | Match class | Scope | Binding decisive numbers |",
        "|---|---|---|---|---|",
    ]
    for r in records:
        src = r["constraint_projection"]["source"]
        nums = []
        for c in r["decisive_claims"]:
            if c.get("binding", True):
                nums.extend(numeric_tokens(c["display"]))
        nums_text = ", ".join(f"`{x}`" for x in dict.fromkeys(nums)) or "textual premise only"
        match_class = (
            "CONSTRAINTS-equivalent"
            if src["path"] == "docs/CONSTRAINTS.md"
            else "binding governance source; no matching CONSTRAINTS bullet"
        )
        scope = r["scope"].replace("|", "\\|")
        lines.append(
            f"| `{r['id']}` | `{src['path']}` ({src.get('locator','')}) | "
            f"{match_class} | {scope} | {nums_text} |"
        )
    lines += [
        "",
        "## Interpretation",
        "",
        "- Equality here means scope and decisive-number equivalence, not byte identity with the",
        "  existing hand-written bullet.",
        "- Nine scientific/hypothesis records map to existing `docs/CONSTRAINTS.md` bullets.",
        "  The two owner decisions are governed by `docs/STATE.md`; they have no matching",
        "  CONSTRAINTS bullet, and the report marks that absence rather than inventing equivalence.",
        "- `void-premise` records are represented but excluded from scientific closure counts.",
        "- The source `docs/CONSTRAINTS.md` remains untouched until the pilot is reviewed.",
        "",
    ]
    return "\n".join(lines)

def expected_outputs(records: list[dict[str, Any]]) -> dict[str, str]:
    return {
        "decision-evidence-index.yaml": render_yaml(records),
        "DECISION-EVIDENCE-INDEX.md": render_index(records),
        "CONSTRAINTS-PILOT-PROJECTION.md": render_constraints(records),
        "equivalence-report.md": render_equivalence(records),
    }

def build(repo_root: Path, check: bool = False) -> dict[str, str]:
    out_dir = repo_root / "docs/evidence/generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    records = load_records(repo_root)
    outputs = expected_outputs(records)
    if check:
        mismatches = []
        for name, content in outputs.items():
            path = out_dir / name
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                mismatches.append(name)
        if mismatches:
            raise SystemExit("generated outputs differ: " + ", ".join(mismatches))
    else:
        for name, content in outputs.items():
            (out_dir / name).write_text(content, encoding="utf-8")
        hashes = {name: hashlib.sha256(content.encode()).hexdigest() for name, content in outputs.items()}
        manifest = {
            "schema": "decision-evidence-pilot-manifest-v1",
            "record_count": len(records),
            "closure_count_excluding_void": sum(r["status"] in {"closed", "invalidated"} for r in records),
            "void_premise_count": sum(r["status"] == "void-premise" for r in records),
            "generated_sha256": hashes,
        }
        (out_dir / "manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
    return outputs

def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    build(args.repo_root, check=args.check)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
