#!/usr/bin/env python3
"""Generate the sole frozen workspace/bounds-elided K2 Rust D11 actor."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

from cgauto.generate_d11_actor_rust import KERNEL_BEGIN, KERNEL_END, generate_source


PROTOCOL_SHA256 = "8741b9e14d1462e940dd72289100fca3af49e91bc210b3fc95fe5dfa447545bc"


OPTIMIZED_STRUCTS = """struct Layer{o:usize,i:usize,k:usize,w:Vec<f32>,b:Vec<f32>}
struct Workspace{input:Vec<f32>,hidden:Vec<f32>,scratch:Vec<f32>,residual:Vec<f32>}
struct Actor{layers:Vec<Layer>,workspace:Workspace}
"""


OPTIMIZED_IMPL = """impl Actor{
    fn new()->Self{
        let payload=decode_payload();
        let mut layers=Vec::with_capacity(META.len());
        for &(o,i,k,wo,so,bo) in &META{
            let mut weights=Vec::with_capacity(o*i*k*k);
            for output in 0..o{
                let scale=read_f32(&payload,so+4*output);
                let start=wo+output*i*k*k;
                for offset in 0..i*k*k{
                    weights.push((payload[start+offset] as i8) as f32*scale);
                }
            }
            let bias=(0..o).map(|output|read_f32(&payload,bo+4*output)).collect();
            layers.push(Layer{o,i,k,w:weights,b:bias});
        }
        let workspace=Workspace{
            input:vec![0.0f32;OBS_C*AREA],
            hidden:vec![0.0f32;16*AREA],
            scratch:vec![0.0f32;16*AREA],
            residual:vec![0.0f32;16*AREA],
        };
        Self{layers,workspace}
    }

    fn convolution(layer:&Layer,input:&[f32],output:&mut[f32],relu:bool){
        let pad=layer.k/2;
        for oc in 0..layer.o{
            for y in 0..H{
                let ky_start=pad.saturating_sub(y);
                let ky_end=(H+pad-y).min(layer.k);
                for x in 0..W{
                    let kx_start=pad.saturating_sub(x);
                    let kx_end=(W+pad-x).min(layer.k);
                    let mut sum=unsafe{*layer.b.get_unchecked(oc)};
                    for ic in 0..layer.i{
                        for ky in ky_start..ky_end{
                            let input_row=ic*AREA+(y+ky-pad)*W;
                            let weight_row=((oc*layer.i+ic)*layer.k+ky)*layer.k;
                            for kx in kx_start..kx_end{
                                unsafe{
                                    sum+=*input.get_unchecked(input_row+x+kx-pad)
                                        **layer.w.get_unchecked(weight_row+kx);
                                }
                            }
                        }
                    }
                    let value=if relu&&sum<0.0{0.0}else{sum};
                    unsafe{*output.get_unchecked_mut(oc*AREA+y*W+x)=value;}
                }
            }
        }
    }

    fn forward(&mut self,observation:&[u8],logits:&mut[f32]){
        let layers=&self.layers;
        let workspace=&mut self.workspace;
        for index in 0..workspace.input.len(){
            unsafe{
                *workspace.input.get_unchecked_mut(index)=
                    (*observation.get_unchecked(index) as f32)*(1.0f32/255.0f32);
            }
        }
        Self::convolution(&layers[0],&workspace.input,&mut workspace.hidden,true);
        for block in 0..4{
            Self::convolution(&layers[1+2*block],&workspace.hidden,&mut workspace.scratch,true);
            Self::convolution(&layers[2+2*block],&workspace.scratch,&mut workspace.residual,false);
            for index in 0..workspace.hidden.len(){
                unsafe{
                    let sum=*workspace.hidden.get_unchecked(index)
                        +*workspace.residual.get_unchecked(index);
                    *workspace.hidden.get_unchecked_mut(index)=if sum<0.0{0.0}else{sum};
                }
            }
        }
        Self::convolution(&layers[9],&workspace.hidden,logits,false);
    }
}
"""


def _replace_exactly_once(source: str, old: str, new: str) -> str:
    if source.count(old) != 1:
        raise ValueError(f"expected exactly one source anchor, found {source.count(old)}")
    return source.replace(old, new, 1)


def generate_optimized_source(
    manifest: dict[str, Any], payload: bytes
) -> tuple[str, dict[str, int | str]]:
    source, accounting = generate_source(manifest, payload)
    source = _replace_exactly_once(
        source,
        "// Generated by cgauto/generate_d11_actor_rust.py; do not edit.",
        "// Generated by cgauto/generate_d11_actor_rust_k2.py; do not edit.",
    )
    source = _replace_exactly_once(
        source,
        "struct Layer{o:usize,i:usize,k:usize,w:Vec<f32>,b:Vec<f32>}\n"
        "struct Actor{layers:Vec<Layer>}\n",
        OPTIMIZED_STRUCTS,
    )
    implementation_start = source.index("impl Actor{")
    implementation_end = source.index("\nfn masked_argmax", implementation_start)
    source = source[:implementation_start] + OPTIMIZED_IMPL + source[implementation_end:]
    if source.count("let actor=Actor::new();") != 2:
        raise ValueError("unexpected actor initialization anchors")
    source = source.replace("let actor=Actor::new();", "let mut actor=Actor::new();")

    encoded = source.encode("utf-8")
    kernel_start = source.index(KERNEL_BEGIN)
    kernel_stop = source.index(KERNEL_END, kernel_start) + len(KERNEL_END)
    accounting = dict(accounting)
    accounting.update(
        {
            "generator_variant": "workspace-bounds-elided-k2",
            "protocol_sha256": PROTOCOL_SHA256,
            "kernel_bytes_including_payload": len(source[kernel_start:kernel_stop].encode("utf-8")),
            "parity_benchmark_harness_bytes": len(source[kernel_stop:].encode("utf-8")),
            "generated_source_bytes": len(encoded),
            "generated_source_sha256": hashlib.sha256(encoded).hexdigest(),
        }
    )
    return source, accounting


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", type=Path)
    parser.add_argument("payload", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    payload = args.payload.read_bytes()
    source, result = generate_optimized_source(manifest, payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source, encoding="utf-8")
    result.update(
        {
            "manifest_path": str(args.manifest.resolve()),
            "manifest_sha256": hashlib.sha256(args.manifest.read_bytes()).hexdigest(),
            "payload_path": str(args.payload.resolve()),
            "output_path": str(args.output.resolve()),
            "under_100000_bytes": len(source.encode("utf-8")) < 100_000,
        }
    )
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
