#!/usr/bin/env python3
"""Generate the frozen standalone Rust kernel for the compact D11 actor."""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
from pathlib import Path
from typing import Any


EXPECTED_FORMAT = "troll-farm-spatial-actor-int8-per-output-v1"
EXPECTED_OBSERVATION_SHAPE = [104, 11, 22]
EXPECTED_ACTION_SHAPE = [13, 11, 22]
EXPECTED_LAYER_NAMES = [
    "stem.0",
    "tower.0.conv1",
    "tower.0.conv2",
    "tower.1.conv1",
    "tower.1.conv2",
    "tower.2.conv1",
    "tower.2.conv2",
    "tower.3.conv1",
    "tower.3.conv2",
    "actor",
]
KERNEL_BEGIN = "// BEGIN_D11_ACTOR_KERNEL\n"
KERNEL_END = "// END_D11_ACTOR_KERNEL\n"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _validated_metadata(manifest: dict[str, Any], payload: bytes) -> str:
    if manifest.get("format") != EXPECTED_FORMAT:
        raise ValueError(f"unexpected export format {manifest.get('format')!r}")
    if manifest.get("observation_shape") != EXPECTED_OBSERVATION_SHAPE:
        raise ValueError("unexpected observation shape")
    if manifest.get("action_shape") != EXPECTED_ACTION_SHAPE:
        raise ValueError("unexpected action shape")
    if manifest.get("payload_bytes") != len(payload):
        raise ValueError("payload length differs from manifest")
    if manifest.get("payload_sha256") != sha256_bytes(payload):
        raise ValueError("payload hash differs from manifest")

    layers = manifest.get("layers")
    if not isinstance(layers, list) or [layer.get("name") for layer in layers] != EXPECTED_LAYER_NAMES:
        raise ValueError("unexpected actor layer order")
    metadata: list[str] = []
    for expected_index, layer in enumerate(layers):
        shape = layer.get("weight_shape")
        if layer.get("index") != expected_index or not isinstance(shape, list) or len(shape) != 4:
            raise ValueError(f"invalid layer metadata at index {expected_index}")
        output_channels, input_channels, kernel_height, kernel_width = map(int, shape)
        if kernel_height != kernel_width or layer.get("kernel") != [kernel_height, kernel_width]:
            raise ValueError(f"unsupported non-square kernel at index {expected_index}")
        weight_offset = int(layer["weight_offset"])
        scale_offset = int(layer["scale_offset"])
        bias_offset = int(layer["bias_offset"])
        weight_bytes = int(layer["weight_bytes"])
        scale_bytes = int(layer["scale_bytes"])
        bias_bytes = int(layer["bias_bytes"])
        if weight_bytes != output_channels * input_channels * kernel_height * kernel_width:
            raise ValueError(f"invalid weight extent at index {expected_index}")
        if scale_bytes != output_channels * 4 or bias_bytes != output_channels * 4:
            raise ValueError(f"invalid scale/bias extent at index {expected_index}")
        if not (
            0 <= weight_offset <= weight_offset + weight_bytes <= len(payload)
            and 0 <= scale_offset <= scale_offset + scale_bytes <= len(payload)
            and 0 <= bias_offset <= bias_offset + bias_bytes <= len(payload)
        ):
            raise ValueError(f"invalid payload offsets at index {expected_index}")
        metadata.append(
            f"({output_channels},{input_channels},{kernel_height},"
            f"{weight_offset},{scale_offset},{bias_offset})"
        )
    return ",".join(metadata)


def generate_source(manifest: dict[str, Any], payload: bytes) -> tuple[str, dict[str, int | str]]:
    """Return one dependency-free Rust 2021 source and deterministic size accounting."""

    metadata = _validated_metadata(manifest, payload)
    encoded = base64.b64encode(payload).decode("ascii")
    payload_sha = sha256_bytes(payload)

    prefix = """// Generated by cgauto/generate_d11_actor_rust.py; do not edit.
#![allow(clippy::needless_range_loop)]
use std::io::{self, Read, Write};
use std::time::Instant;

"""
    kernel = f"""{KERNEL_BEGIN}const H:usize=11;
const W:usize=22;
const AREA:usize=H*W;
const OBS_C:usize=104;
const ACT_C:usize=13;
const ACTIONS:usize=ACT_C*AREA;
const PAYLOAD_LEN:usize={len(payload)};
const PAYLOAD_SHA256:&str=\"{payload_sha}\";
const PAYLOAD_B64:&str=\"{encoded}\";
const META:[(usize,usize,usize,usize,usize,usize);10]=[{metadata}];

struct Layer{{o:usize,i:usize,k:usize,w:Vec<f32>,b:Vec<f32>}}
struct Actor{{layers:Vec<Layer>}}

fn b64_value(byte:u8)->Option<u8>{{
    match byte{{
        b'A'..=b'Z'=>Some(byte-b'A'),
        b'a'..=b'z'=>Some(byte-b'a'+26),
        b'0'..=b'9'=>Some(byte-b'0'+52),
        b'+'=>Some(62),b'/'=>Some(63),b'='=>None,_=>None,
    }}
}}

fn decode_payload()->Vec<u8>{{
    let source=PAYLOAD_B64.as_bytes();
    let mut out=Vec::with_capacity(PAYLOAD_LEN);
    let mut index=0;
    while index<source.len(){{
        let a=b64_value(source[index]).unwrap() as u32;
        let b=b64_value(source[index+1]).unwrap() as u32;
        let c=b64_value(source[index+2]);
        let d=b64_value(source[index+3]);
        out.push(((a<<2)|(b>>4)) as u8);
        if let Some(c)=c{{
            let c=c as u32;
            out.push(((b<<4)|(c>>2)) as u8);
            if let Some(d)=d{{out.push(((c<<6)|(d as u32)) as u8);}}
        }}
        index+=4;
    }}
    assert_eq!(out.len(),PAYLOAD_LEN);
    out
}}

fn read_f32(payload:&[u8],offset:usize)->f32{{
    f32::from_le_bytes(payload[offset..offset+4].try_into().unwrap())
}}

impl Actor{{
    fn new()->Self{{
        let payload=decode_payload();
        let mut layers=Vec::with_capacity(META.len());
        for &(o,i,k,wo,so,bo) in &META{{
            let mut weights=Vec::with_capacity(o*i*k*k);
            for output in 0..o{{
                let scale=read_f32(&payload,so+4*output);
                let start=wo+output*i*k*k;
                for offset in 0..i*k*k{{
                    weights.push((payload[start+offset] as i8) as f32*scale);
                }}
            }}
            let bias=(0..o).map(|output|read_f32(&payload,bo+4*output)).collect();
            layers.push(Layer{{o,i,k,w:weights,b:bias}});
        }}
        Self{{layers}}
    }}

    fn convolution(layer:&Layer,input:&[f32],output:&mut[f32],relu:bool){{
        let pad=layer.k/2;
        for oc in 0..layer.o{{
            for y in 0..H{{
                for x in 0..W{{
                    let mut sum=layer.b[oc];
                    for ic in 0..layer.i{{
                        for ky in 0..layer.k{{
                            let shifted_y=y+ky;
                            if shifted_y<pad||shifted_y>=H+pad{{continue;}}
                            let iy=shifted_y-pad;
                            for kx in 0..layer.k{{
                                let shifted_x=x+kx;
                                if shifted_x<pad||shifted_x>=W+pad{{continue;}}
                                let ix=shifted_x-pad;
                                let wi=(((oc*layer.i+ic)*layer.k+ky)*layer.k)+kx;
                                sum+=input[ic*AREA+iy*W+ix]*layer.w[wi];
                            }}
                        }}
                    }}
                    output[oc*AREA+y*W+x]=if relu&&sum<0.0{{0.0}}else{{sum}};
                }}
            }}
        }}
    }}

    fn forward(&self,observation:&[u8],logits:&mut[f32]){{
        let mut input=vec![0.0f32;OBS_C*AREA];
        for index in 0..input.len(){{input[index]=(observation[index] as f32)*(1.0f32/255.0f32);}}
        let mut hidden=vec![0.0f32;16*AREA];
        let mut scratch=vec![0.0f32;16*AREA];
        Self::convolution(&self.layers[0],&input,&mut hidden,true);
        for block in 0..4{{
            Self::convolution(&self.layers[1+2*block],&hidden,&mut scratch,true);
            let mut residual=vec![0.0f32;16*AREA];
            Self::convolution(&self.layers[2+2*block],&scratch,&mut residual,false);
            for index in 0..hidden.len(){{hidden[index]=(hidden[index]+residual[index]).max(0.0);}}
        }}
        Self::convolution(&self.layers[9],&hidden,logits,false);
    }}
}}

fn masked_argmax(logits:&[f32],mask:&[u8])->usize{{
    let mut best=usize::MAX;
    let mut value=f32::NEG_INFINITY;
    for index in 0..ACTIONS{{
        if mask[index]!=0&&(best==usize::MAX||logits[index]>value){{best=index;value=logits[index];}}
    }}
    assert_ne!(best,usize::MAX);
    best
}}
{KERNEL_END}"""
    harness = """const INPUT_MAGIC:&[u8;8]=b\"TFD11IN1\";
const OUTPUT_MAGIC:&[u8;8]=b\"TFD11OU1\";

fn read_input()->io::Result<(Vec<u8>,Vec<u8>,usize)>{
    let mut data=Vec::new();io::stdin().read_to_end(&mut data)?;
    if data.len()<12||&data[..8]!=INPUT_MAGIC{return Err(io::Error::new(io::ErrorKind::InvalidData,"input header"));}
    let count=u32::from_le_bytes(data[8..12].try_into().unwrap()) as usize;
    let observations=count*OBS_C*AREA;
    let masks=count*ACTIONS;
    if data.len()!=12+observations+masks{return Err(io::Error::new(io::ErrorKind::InvalidData,"input length"));}
    Ok((data[12..12+observations].to_vec(),data[12+observations..].to_vec(),count))
}

fn parity()->io::Result<()>{
    let (observations,masks,count)=read_input()?;
    let actor=Actor::new();
    let mut output=io::BufWriter::new(io::stdout().lock());
    output.write_all(OUTPUT_MAGIC)?;output.write_all(&(count as u32).to_le_bytes())?;
    let mut logits=vec![0.0f32;ACTIONS];
    for sample in 0..count{
        actor.forward(&observations[sample*OBS_C*AREA..(sample+1)*OBS_C*AREA],&mut logits);
        for &value in &logits{output.write_all(&value.to_le_bytes())?;}
        let action=masked_argmax(&logits,&masks[sample*ACTIONS..(sample+1)*ACTIONS]);
        output.write_all(&(action as u32).to_le_bytes())?;
    }
    output.flush()
}

fn benchmark(iterations:usize)->io::Result<()>{
    let (observations,masks,count)=read_input()?;
    if count<2{return Err(io::Error::new(io::ErrorKind::InvalidData,"benchmark needs two samples"));}
    let initialization=Instant::now();
    let actor=Actor::new();
    let mut first_checksum=0usize;
    let mut logits=vec![0.0f32;ACTIONS];
    for worker in 0..2{
        actor.forward(&observations[worker*OBS_C*AREA..(worker+1)*OBS_C*AREA],&mut logits);
        first_checksum^=masked_argmax(&logits,&masks[worker*ACTIONS..(worker+1)*ACTIONS]);
    }
    let initialization_first_pair_ns=initialization.elapsed().as_nanos() as u64;
    for warmup in 0..16{
        for worker in 0..2{
            let sample=(2*warmup+worker)%count;
            actor.forward(&observations[sample*OBS_C*AREA..(sample+1)*OBS_C*AREA],&mut logits);
            first_checksum^=masked_argmax(&logits,&masks[sample*ACTIONS..(sample+1)*ACTIONS]);
        }
    }
    let mut durations=Vec::with_capacity(iterations);
    let mut checksum=first_checksum;
    for iteration in 0..iterations{
        let started=Instant::now();
        for worker in 0..2{
            let sample=(2*iteration+worker)%count;
            actor.forward(&observations[sample*OBS_C*AREA..(sample+1)*OBS_C*AREA],&mut logits);
            checksum=checksum.wrapping_add(masked_argmax(&logits,&masks[sample*ACTIONS..(sample+1)*ACTIONS]));
        }
        durations.push(started.elapsed().as_nanos() as u64);
    }
    durations.sort_unstable();
    let median=durations[durations.len()/2];
    let p95=durations[((durations.len()*95+99)/100).saturating_sub(1)];
    let maximum=*durations.last().unwrap();
    println!("{{\\\"iterations\\\":{},\\\"warmup_pairs\\\":16,\\\"initialization_first_pair_ns\\\":{},\\\"median_pair_ns\\\":{},\\\"p95_pair_ns\\\":{},\\\"maximum_pair_ns\\\":{},\\\"checksum\\\":{},\\\"payload_sha256\\\":\\\"{}\\\"}}",iterations,initialization_first_pair_ns,median,p95,maximum,checksum,PAYLOAD_SHA256);
    Ok(())
}

fn main()->io::Result<()>{
    let mut args=std::env::args();let _=args.next();
    if args.next().as_deref()==Some("--bench"){
        let iterations=args.next().and_then(|value|value.parse().ok()).unwrap_or(1000);
        if iterations==0{return Err(io::Error::new(io::ErrorKind::InvalidInput,"zero iterations"));}
        benchmark(iterations)
    }else{parity()}
}
"""
    source = prefix + kernel + harness
    encoded_source = source.encode("utf-8")
    kernel_bytes = len(kernel.encode("utf-8"))
    accounting: dict[str, int | str] = {
        "payload_bytes": len(payload),
        "payload_base64_bytes": len(encoded),
        "kernel_bytes_including_payload": kernel_bytes,
        "parity_benchmark_harness_bytes": len(harness.encode("utf-8")),
        "generated_source_bytes": len(encoded_source),
        "generated_source_sha256": sha256_bytes(encoded_source),
        "payload_sha256": payload_sha,
    }
    return source, accounting


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", type=Path)
    parser.add_argument("payload", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    payload = args.payload.read_bytes()
    source, result = generate_source(manifest, payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source, encoding="utf-8")
    result.update(
        {
            "manifest_path": str(args.manifest.resolve()),
            "manifest_sha256": sha256_bytes(args.manifest.read_bytes()),
            "payload_path": str(args.payload.resolve()),
            "output_path": str(args.output.resolve()),
            "under_100000_bytes": len(source.encode("utf-8")) < 100_000,
        }
    )
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
