#!/usr/bin/env python3
"""Render the frozen D64a snapshot model as dependency-free Rust constants."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent
MODEL = (
    REPO
    / "data/analysis/live-agent-6553250"
    / "d64a-field-snapshot-model-2026-07-21.json"
)
EXPECTED_MODEL_SHA256 = (
    "89144ab75a55fba17bbed18975f2f8fa636310a2e4e5ea2650f228ea155e67d0"
)


def rust_float(value: float) -> str:
    rendered = repr(float(value))
    if "e" not in rendered and "." not in rendered:
        rendered += ".0"
    return rendered


def render(model: dict) -> str:
    features = model["features"]
    if model["schema"] != "troll-farm-d64a-snapshot-model-v1" or len(features) != 44:
        raise ValueError("unexpected D64a model artifact")
    names = [feature["name"] for feature in features]
    if names != sorted(names) or len(set(names)) != len(names):
        raise ValueError("D64a feature order is not unique/sorted")

    def array(field: str) -> str:
        return ",\n    ".join(rust_float(feature[field]) for feature in features)

    quoted_names = ",\n    ".join(json.dumps(name) for name in names)
    return f"""// Generated by cgauto/generate_d64a_rust_model.py; do not hand-edit.
pub const FEATURE_COUNT: usize = 44;
pub const THRESHOLD: f64 = {rust_float(model['threshold'])};
pub const SUPPORT_RADIUS_RMS_Z_P95: f64 = {rust_float(model['support_radius_rms_z_p95'])};
pub const INTERCEPT: f64 = {rust_float(model['fit']['intercept'])};
pub const FEATURE_NAMES: [&str; FEATURE_COUNT] = [
    {quoted_names}
];
pub const MEANS: [f64; FEATURE_COUNT] = [
    {array('mean')}
];
pub const SCALES: [f64; FEATURE_COUNT] = [
    {array('scale')}
];
pub const COEFFICIENTS: [f64; FEATURE_COUNT] = [
    {array('standardized_coefficient')}
];
"""


def load_model() -> dict:
    digest = hashlib.sha256(MODEL.read_bytes()).hexdigest()
    if digest != EXPECTED_MODEL_SHA256:
        raise ValueError(f"D64a model hash mismatch: {digest}")
    return json.loads(MODEL.read_text())


def write_new(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("x") as handle:
        handle.write(text)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    source = render(load_model())
    write_new(args.output, source)
    print(
        json.dumps(
            {
                "bytes": len(source.encode()),
                "sha256": hashlib.sha256(source.encode()).hexdigest(),
                "output": str(args.output),
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()

