#!/usr/bin/env python3
"""Expand exact orchard variants readably while preserving their token streams."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import sys
from pathlib import Path
from typing import Any


REPO = Path(__file__).resolve().parents[2]
SOURCES = {
    "with_orchard": {
        "path": Path("cgauto/submissions/candidate-agent6553250-preseed-e7a-lemon-near-tie.min.rs"),
        "sha256": "97bfe71e3f2f05e1b8fa3c697c5e5db3624ac9739e90954e9fa9be79a8e48595",
        "output": "e7a-with-orchard-readable.rs",
    },
    "activation_disabled": {
        "path": Path("claude_1/orchard-code-cost/activation-disabled-reference.rs"),
        "sha256": "8fc1b7f3499a407e5df546bbc688843c56c0f6e7d9382b18ba359592b586693d",
        "output": "e7a-activation-disabled-readable.rs",
    },
    "orchard_stripped": {
        "path": Path("claude_1/orchard-code-cost/e7a-without-orchard-code.rs"),
        "sha256": "102caecde916b03dde0c02d1d8c13c9333b6ee3a26f13df34ad21fbebaae0fd6",
        "output": "e7a-without-orchard-readable.rs",
    },
}


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def load_compactor():
    path = REPO / "cgauto/compact_rust_source.py"
    spec = importlib.util.spec_from_file_location("readable_orchard_compactor", path)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load canonical Rust compactor")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def expand(source: str, compactor: Any, label: str, digest: str) -> str:
    pieces = [
        f"// Canonical readable expansion: {label}.\n",
        f"// Compact parent SHA-256: {digest}.\n",
        "// Generated by build_readable_orchard_cost.py; only comments and whitespace added.\n",
        "// Compacting this file and restoring the lineage newline reproduces the parent exactly.\n",
        "\n",
    ]
    tokens = compactor._tokens(source)
    depth = 0
    at_line_start = True

    def newline(indent: int) -> None:
        nonlocal at_line_start
        pieces.append("\n" + "    " * max(indent, 0))
        at_line_start = True

    for separated, token in tokens:
        text = token.text
        if text == "}":
            depth -= 1
            if not at_line_start:
                newline(depth)
        if not at_line_start and separated:
            pieces.append(" ")
        pieces.append(text)
        at_line_start = False
        if text == "{":
            depth += 1
            newline(depth)
        elif text in {";", "}"}:
            newline(depth)
    return "".join(pieces).rstrip() + "\n"


def line_metrics(text: str) -> dict[str, int]:
    lines = text.splitlines()
    blank = sum(not line.strip() for line in lines)
    comment = sum(line.lstrip().startswith("//") for line in lines)
    return {
        "physical_lines": len(lines),
        "blank_lines": blank,
        "comment_only_lines": comment,
        "code_lines": len(lines) - blank - comment,
        "nonblank_lines": len(lines) - blank,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    compactor = load_compactor()
    output_dir = args.output_dir.resolve()
    manifest_path = args.manifest.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    records: dict[str, Any] = {}

    for label, specification in SOURCES.items():
        source_path = REPO / specification["path"]
        raw = source_path.read_bytes()
        if sha256(raw) != specification["sha256"]:
            raise RuntimeError(f"{label}: compact parent hash mismatch")
        source = raw.decode("utf-8")
        readable = expand(source, compactor, label, specification["sha256"])
        output = output_dir / specification["output"]
        if output.exists() and not args.force:
            raise RuntimeError(f"refusing to overwrite {output}")
        output.write_text(readable, encoding="utf-8")

        compacted = compactor.compact(readable).encode("utf-8")
        normalized = compacted + (b"\n" if raw.endswith(b"\n") else b"")
        if normalized != raw:
            raise RuntimeError(f"{label}: readable round trip changed compact parent")
        records[label] = {
            "compact_path": str(specification["path"]),
            "compact_bytes": len(raw),
            "compact_sha256": sha256(raw),
            "readable_path": str(output.relative_to(REPO)),
            "readable_bytes": len(readable.encode("utf-8")),
            "readable_sha256": sha256(readable.encode("utf-8")),
            "round_trip_exact": True,
            **line_metrics(readable),
        }

    baseline = records["with_orchard"]
    disabled = records["activation_disabled"]
    stripped = records["orchard_stripped"]
    result = {
        "schema": "troll-farm-readable-orchard-code-cost-v1",
        "generator": str(Path(__file__).resolve().relative_to(REPO)),
        "sources": records,
        "line_cost": {
            "physical_lines_removed_vs_baseline": baseline["physical_lines"] - stripped["physical_lines"],
            "code_lines_removed_vs_baseline": baseline["code_lines"] - stripped["code_lines"],
            "activation_edit_physical_lines": baseline["physical_lines"] - disabled["physical_lines"],
            "physical_implementation_lines_removed_after_disable": disabled["physical_lines"] - stripped["physical_lines"],
            "formatting_definition": "one line after every brace or semicolon, four-space brace indentation, common four-line generated header",
        },
        "canonical_character_cost": 15013,
        "sacred_source_modified": False,
    }
    if manifest_path.exists() and not args.force:
        raise RuntimeError(f"refusing to overwrite {manifest_path}")
    manifest_path.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(result["line_cost"], sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
