#!/usr/bin/env python3
"""DIAGNOSTIC ONLY — what the panel looks like with `W = 1` instead of `W = 2`.

This is **not a candidate** and nothing here is proposed for submission. The chartered candidate
is `W = 2`; the charter fixed it and codex_1's G-0 ruled on it. What `d4_attribution.py` shows is
that D-4's slack is exactly one turn and `W = 2` spends two, which makes 96 of the candidate's
102 D-4 episodes hold-shaped. The obvious question a reviewer will ask next is *what does W = 1
cost and buy*, and answering it costs one flag and one 240-game panel run, so it is answered here
rather than left for another wake.

The arm is generated from `arm-candidate.rs` by rewriting the single `HOLD_WINDOW` line. It is
written to `diag-w1-candidate.rs`, whose name says what it is, and it is excluded from
`arm-manifest.json` so that no downstream tool can mistake it for one of the three chartered arms.

    python3 claude_1/cure1/diagnostic_w1.py
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
SRC = HERE / "arm-candidate.rs"
DIAG = HERE / "diag-w1-candidate.rs"
CONFIG = HERE / "cure1-diag-w1-config.json"
GAMES = "/tmp/claude-1000/cure1/cure1-diag-w1/games"
OLD = "            const HOLD_WINDOW:u8=2;"
NEW = "            const HOLD_WINDOW:u8=1;"


def main() -> int:
    text = SRC.read_text()
    if text.count(OLD) != 1:
        print(f"REFUSED: the HOLD_WINDOW line occurs {text.count(OLD)} times in {SRC.name}")
        return 2
    diag = text.replace(OLD, NEW)
    DIAG.write_text(diag)
    sha = hashlib.sha256(diag.encode()).hexdigest()
    print(f"  wrote {DIAG.name}  sha256 {sha[:16]}  (W=1, DIAGNOSTIC, not a candidate)")

    cfg = json.loads((HERE / "cure1-candidate-config.json").read_text())
    cfg["task"] = ("20260825-dance-cure-candidate-1-hold DIAGNOSTIC panel: W=1 variant of the "
                   "candidate arm vs the champion base 547fa706 — NOT a candidate")
    cfg["candidate"] = {"crate": "cure1_diag_w1_seat_a", "sha256": sha,
                        "source": "../../claude_1/cure1/diag-w1-candidate.rs"}
    cfg["games_dir"] = GAMES
    cfg["notes"] = ["DIAGNOSTIC ONLY. Generated by claude_1/cure1/diagnostic_w1.py to price the "
                    "W=1 alternative against the D-4 finding. Not chartered, not submitted, not "
                    "in arm-manifest.json.", cfg["notes"][1]]
    CONFIG.write_text(json.dumps(cfg, indent=2, sort_keys=True) + "\n")

    rc = subprocess.run(
        [sys.executable, str(REPO / "claude_1/pipeline/fuzz_panel.py"), "--config", str(CONFIG),
         "--report", str(HERE / "results" / "panel-diag-w1.md"),
         "--json", str(HERE / "results" / "panel-diag-w1.json")],
        capture_output=True, text=True, timeout=3600)
    print("  " + (rc.stdout.strip().split("\n")[-1] if rc.stdout.strip() else rc.stderr[-400:]))
    rc2 = subprocess.run(
        [sys.executable, str(HERE / "panel_costs.py"),
         "--candidate-games", f"{GAMES}/games.jsonl.gz",
         "--json", str(HERE / "results" / "panel-named-costs-diag-w1.json")],
        capture_output=True, text=True, timeout=3600)
    print(rc2.stdout or rc2.stderr[-2000:])
    return 0


if __name__ == "__main__":
    sys.exit(main())
