#!/usr/bin/env python3
"""Derive the 47-branch ledger's tallies from data instead of counting by hand.

`chatgpt_1`'s bite-test audit r2 (`20260812T003000Z`, blocker 5) found that the
47-branch ledger and its headline counts were hand-maintained. The audit says
the figures are "counted from the table above", which is exactly the shape of
claim that is true when written and silently false after the next edit — the
same defect `render_ledger.py` already closed for the mutation tables (BAR-1).

This renders both the table and the four tallies from
``branch_ledger.json``. It is the projection; the JSON is the source.

    python3 render_branch_ledger.py             # write results/branch-ledger.md
    python3 render_branch_ledger.py --check     # exit 2 if the audit's prose
                                                # disagrees with the data
"""
from __future__ import annotations

import argparse
import collections
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
LEDGER = os.path.join(HERE, "branch_ledger.json")
OUT = os.path.join(HERE, "results", "branch-ledger.md")
AUDIT = os.path.join(os.path.dirname(HERE),
                     "detector-bitetest-audit-2026-08-08.md")

AXES = (
    ("applicability", "applicability",
     ["APPLICABLE", "INSTRUMENT_UNSUPPORTED"]),
    ("contract authority", "contract_authority", ["SETTLED", "CONFLICT"]),
    ("implementation validity", "impl_validity",
     ["PINNED", "PARTIAL", "UNPINNED", "NO_FIXTURE"]),
    ("truth validity", "truth_validity",
     ["VALIDATED_BY_DEFINITION", "GATE_UNREADY", "UNRESOLVED"]),
)


def load():
    with open(LEDGER, encoding="utf-8") as fh:
        return json.load(fh)


def tallies(branches):
    """axis label -> {value: count}, in the axis's declared order.

    Values are emitted even at zero: an axis value that silently vanishes when
    it stops occurring is how a shrinking denominator hides.
    """
    out = {}
    for label, key, order in AXES:
        seen = collections.Counter(b[key] for b in branches)
        unknown = sorted(v for v in seen if v not in order)
        if unknown:
            raise SystemExit("branch_ledger.json: %s has values outside its "
                             "declared axis: %s" % (key, unknown))
        out[label] = {value: seen.get(value, 0) for value in order}
    return out


def render(doc) -> str:
    branches = doc["branches"]
    lines = [
        "# Detector branch ledger — generated",
        "",
        "Generated by `bitetest-audit/render_branch_ledger.py` from",
        "`bitetest-audit/branch_ledger.json`. Do not hand-edit: edit the JSON.",
        "",
        "**%d branch rows.**" % len(branches),
        "",
        "| Branch | Governing authority | Evidence that exists | Impl. validity"
        " | Applicability | Contract authority | Truth validity |",
        "|---|---|---|---|---|---|---|",
    ]
    for b in branches:
        lines.append("| %s | %s | %s | %s | %s | %s | %s |" % (
            b["branch"], b["governing_authority"], b["evidence"],
            b["impl_validity_note"], b["applicability_note"],
            b["contract_authority"], b["truth_validity_note"]))
    lines += ["", "## Counts over the %d branch rows" % len(branches), "",
              "Derived, not transcribed.", "", "| axis | tally |", "|---|---|"]
    for label, counts in tallies(branches).items():
        lines.append("| %s | %s |" % (
            label, ", ".join("%d `%s`" % (n, v) for v, n in counts.items())))
    no_fixture = sum(1 for b in branches if b["impl_validity"] == "NO_FIXTURE")
    lines += [
        "",
        "**%d of %d branches have no fixture at all.** That, not the kill rate, "
        "is the load-bearing measurement in this audit." % (no_fixture, len(branches)),
        "",
    ]
    return "\n".join(lines)


def check(doc) -> int:
    """Assert the audit's published tallies equal the derived ones.

    Reads the four figures out of the audit's own prose so that drift between
    the document and the data is a failure rather than something a reader has
    to notice.
    """
    with open(AUDIT, encoding="utf-8") as fh:
        text = fh.read()
    derived = tallies(doc["branches"])
    problems = []
    for label, counts in derived.items():
        row = re.search(r"^\|\s*%s\s*\|(.+?)\|\s*$" % re.escape(label),
                        text, re.M)
        if not row:
            problems.append("audit has no `%s` tally row" % label)
            continue
        published = dict((m.group(2), int(m.group(1))) for m in
                         re.finditer(r"(\d+)\s*`([A-Z_]+)`", row.group(1)))
        for value, n in counts.items():
            if n == 0 and value not in published:
                continue
            if published.get(value) != n:
                problems.append(
                    "%s / %s: audit says %s, data says %d"
                    % (label, value, published.get(value, "nothing"), n))
    total = re.search(r"Counts over the (\d+) branch rows", text)
    if total and int(total.group(1)) != len(doc["branches"]):
        problems.append("audit says %s branch rows, data has %d"
                        % (total.group(1), len(doc["branches"])))
    if problems:
        sys.stderr.write("branch ledger drift:\n  %s\n" % "\n  ".join(problems))
        return 2
    print("branch ledger: audit prose matches the data on all %d axes (%d rows)"
          % (len(derived), len(doc["branches"])))
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the audit's prose against the data; exit 2 on drift")
    args = ap.parse_args(argv)
    doc = load()
    if args.check:
        return check(doc)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(render(doc))
    print("wrote %s (%d rows)" % (OUT, len(doc["branches"])))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
