#!/usr/bin/env python3
"""Executable I-30 mutation experiment (review I30R2-10).

Revision 2 committed `mutation-sweep-r2-2026-08-08.txt`, a text report saying
"23/23 caught". A text report is not an experiment: nothing in it could be
re-run, and nothing pinned WHICH bytes were changed. This runner is the
experiment.

For every mutation in the manifest it

  1. verifies the target file's sha256 still matches the pinned value, and
     that the exact `preimage` string occurs EXACTLY ONCE in it (so the patch
     is unambiguous);
  2. copies the whole module directory to a scratch tree;
  3. applies the one-string substitution;
  4. runs `python3 -m unittest test_i30_invariant` in the scratch tree;
  5. records CAUGHT (the suite failed) or SURVIVED (it passed), the exact
     failing test ids, and whether the mutation's declared
     `expected_catcher` was among them.

A mutation is only fully closed when it is CAUGHT **by its expected catcher**:
a mutation caught by an unrelated neighbouring assertion proves the suite is
sensitive, not that the defect's own test bites.

Usage:
  python3 i30/i30_mutation_runner.py \
      --manifest i30/mutation-manifest-r3-2026-08-09.json \
      --out i30/mutation-sweep-r3-2026-08-09.json \
      --text i30/mutation-sweep-r3-2026-08-09.txt

Scope: measurement only. It copies this directory to a temporary tree and
never writes to a bot, candidate, parent, gate, harness, submission or Arena
artifact.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
MODULE_DIR = os.path.dirname(HERE)
TEST_MODULE = "test_i30_invariant"

# `TestR3D10MutationRunnerIsReproducible` asserts the manifest's pinned
# sha256 of each target file. A mutation changes exactly that sha, so the D10
# class would flag EVERY mutation and destroy the attribution the experiment
# exists to establish. It is the machinery's own test, not the instrument's,
# and it is deselected inside the scratch tree only. Everything else runs.
DESELECTED_CLASSES = ("TestR3D10MutationRunnerIsReproducible",)

SUITE_DRIVER = '''"""Generated by i30/i30_mutation_runner.py -- do not commit."""
import sys, unittest
import test_i30_invariant as T
DESELECT = %r
loader = unittest.TestLoader()
suite = unittest.TestSuite()
for name in dir(T):
    obj = getattr(T, name)
    if (isinstance(obj, type) and issubclass(obj, unittest.TestCase)
            and name not in DESELECT):
        suite.addTests(loader.loadTestsFromTestCase(obj))
res = unittest.TextTestRunner(verbosity=1).run(suite)
sys.exit(0 if res.wasSuccessful() else 1)
'''

FAIL_RE = re.compile(r"^(?:FAIL|ERROR): (\S+) \((\S+?)\)", re.M)


def sha256_path(path):
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def failing_test_ids(output):
    """`{ClassName.test_name}` for every failure/error unittest printed."""
    out = set()
    for name, qualified in FAIL_RE.findall(output):
        cls = qualified.split(".")
        # unittest prints `module.Class.test_name`
        if len(cls) >= 2:
            out.add("%s.%s" % (cls[-2], name))
    return out


def make_workdir(root, name):
    """A scratch copy of every python module the suite imports."""
    work = os.path.join(root, name)
    os.makedirs(work)
    for entry in sorted(os.listdir(MODULE_DIR)):
        if entry.endswith(".py"):
            shutil.copy2(os.path.join(MODULE_DIR, entry),
                         os.path.join(work, entry))
    with open(os.path.join(work, "_mutation_suite.py"), "w",
              encoding="utf-8") as fh:
        fh.write(SUITE_DRIVER % (DESELECTED_CLASSES,))
    return work


def run_suite(workdir, timeout=900):
    # the real repository is an INPUT (spec/ruling/review blobs, engine
    # bytes, the owner-decision ref), and a scratch copy has no git refs
    env = dict(os.environ, I30_REPO_ROOT=os.path.abspath(
        os.path.join(MODULE_DIR, "..", "..")))
    proc = subprocess.run([sys.executable, "_mutation_suite.py"],
                          cwd=workdir, stdout=subprocess.PIPE,
                          stderr=subprocess.STDOUT, timeout=timeout, env=env)
    return proc.returncode, proc.stdout.decode("utf-8", "replace")


def patches_of(mutation):
    """Every substitution a mutation applies.

    Most mutations are one string. A DEFENCE-IN-DEPTH guard needs all of its
    copies removed at once, or the mutation is masked by its own redundancy
    and `SURVIVED` says nothing about the guard: `extra_patches` carries the
    rest.
    """
    return [{"target": mutation["target"], "preimage": mutation["preimage"],
             "replacement": mutation["replacement"]}] + list(
                 mutation.get("extra_patches", []))


def apply_mutation(workdir, mutation):
    shas = {}
    for patch in patches_of(mutation):
        path = os.path.join(workdir, patch["target"])
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        count = text.count(patch["preimage"])
        if count != 1:
            return False, ("preimage occurs %d times in %s (must be exactly 1)"
                           % (count, patch["target"]))
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text.replace(patch["preimage"], patch["replacement"]))
        shas[patch["target"]] = sha256_path(path)
    return True, shas


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--manifest",
                    default=os.path.join(HERE,
                                         "mutation-manifest-r3-2026-08-09"
                                         ".json"))
    ap.add_argument("--out", default=None, help="machine-readable JSON result")
    ap.add_argument("--text", default=None, help="human-readable summary")
    ap.add_argument("--only", default=None, help="run one mutation id")
    args = ap.parse_args(argv)

    with open(args.manifest, encoding="utf-8") as fh:
        manifest = json.load(fh)

    pinned = []
    for target, sha in sorted(manifest["target_sha256"].items()):
        actual = sha256_path(os.path.join(MODULE_DIR, target))
        pinned.append({"target": target, "pinned_sha256": sha,
                       "actual_sha256": actual, "matches": actual == sha})

    # the unmutated control: the suite must be green before any mutation
    with tempfile.TemporaryDirectory() as tmp:
        rc, out = run_suite(make_workdir(tmp, "control"))
    # deliberately NO wall-clock line: this artifact must be byte-reproducible
    ran = re.search(r"^Ran (\d+) tests", out, re.M)
    control = {"returncode": rc, "green": rc == 0,
               "failing": sorted(failing_test_ids(out)),
               "tests_run": int(ran.group(1)) if ran else None}

    results = []
    for mutation in manifest["mutations"]:
        if args.only and mutation["id"] != args.only:
            continue
        with tempfile.TemporaryDirectory() as tmp:
            work = make_workdir(tmp, mutation["id"])
            ok, detail = apply_mutation(work, mutation)
            if not ok:
                results.append(dict(mutation, verdict="NOT_APPLIED",
                                    detail=detail))
                continue
            rc, out = run_suite(work)
        failing = sorted(failing_test_ids(out))
        expected = mutation["expected_catcher"]
        results.append({
            "id": mutation["id"], "defect": mutation["defect"],
            "target": mutation["target"],
            "mutated_sha256": detail,
            "patches": len(patches_of(mutation)),
            "expected_catcher": expected,
            "verdict": "CAUGHT" if rc != 0 else "SURVIVED",
            "caught_by_expected": expected in failing,
            "failing_tests": failing,
            "failing_count": len(failing),
        })

    caught = [r for r in results if r["verdict"] == "CAUGHT"]
    by_expected = [r for r in results if r.get("caught_by_expected")]
    report = {
        "manifest": os.path.relpath(args.manifest, MODULE_DIR),
        "manifest_sha256": sha256_path(args.manifest),
        "runner_sha256": sha256_path(os.path.abspath(__file__)),
        "python_version": sys.version.split()[0],
        "target_pins": pinned,
        "control": control,
        "mutations_run": len(results),
        "caught": len(caught),
        "survived": len(results) - len(caught),
        "caught_by_expected_catcher": len(by_expected),
        "results": results,
    }
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            json.dump(report, fh, indent=2, sort_keys=True)
            fh.write("\n")

    lines = ["I-30 revision-3 mutation sweep",
             "manifest: %s (sha256 %s)" % (report["manifest"],
                                           report["manifest_sha256"]),
             "runner  : i30/i30_mutation_runner.py (sha256 %s)"
             % report["runner_sha256"],
             "python  : %s" % report["python_version"],
             "control : %s (%d failing)"
             % ("GREEN" if control["green"] else "RED",
                len(control["failing"])),
             "",
             "%-14s %-6s %-10s %-6s  %s"
             % ("id", "defect", "verdict", "by-own", "expected catcher")]
    for r in results:
        lines.append("%-14s %-6s %-10s %-6s  %s"
                     % (r["id"], r["defect"], r["verdict"],
                        "yes" if r.get("caught_by_expected") else "NO",
                        r["expected_catcher"]))
    lines += ["",
              "caught %d/%d; caught by their own expected test %d/%d"
              % (report["caught"], report["mutations_run"],
                 report["caught_by_expected_catcher"],
                 report["mutations_run"]),
              "",
              "This is descriptive of THIS chosen mutation set. It is not a",
              "completeness proof for the identifiability rules, the",
              "activation contract or the execution gate."]
    text = "\n".join(lines) + "\n"
    if args.text:
        with open(args.text, "w", encoding="utf-8") as fh:
            fh.write(text)
    sys.stdout.write(text)
    # a survivor, or a control that is not green, is a failed experiment
    return 0 if (control["green"] and report["survived"] == 0) else 1


if __name__ == "__main__":
    sys.exit(main())
